language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script: composer install

script: phpunit -c phpunit.xml.dist

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always